// Generated by web_artifact_build from server/src/privileged.ts. Do not edit.
import { definePrivilegedContracts, z } from "@hatch/space-sdk";

export const privileged = definePrivilegedContracts({
  verifyCalendarSyncToken: {
    request: z.object({ token: z.string().min(1).max(500) }),
    response: z.object({ matches: z.boolean() }),
    timeoutMs: 5_000,
  },
  readCalendarWindow: {
    request: z.object({
      time_min: z.string().min(1).max(80),
      time_max: z.string().min(1).max(80),
    }),
    response: z.object({
      ok: z.boolean(),
      error: z.string().optional(),
      events: z.array(z.object({
        google_event_id: z.string(),
        calendar_name: z.enum(["primary", "intent", "tangentcode"]),
        title: z.string(),
        start_time: z.string(),
        end_time: z.string().nullable(),
        location: z.string().nullable(),
        is_all_day: z.boolean(),
      })),
    }),
    timeoutMs: 30_000,
  },
  writeIntentCalendarEvent: {
    request: z.object({
      operation: z.enum(["create", "update", "delete"]),
      event_id: z.string().max(1024).optional(),
      title: z.string().trim().min(1).max(500).optional(),
      start_time: z.string().max(80).optional(),
      end_time: z.string().max(80).optional(),
    }),
    response: z.object({
      ok: z.boolean(),
      error: z.string().optional(),
      event: z.object({
        google_event_id: z.string(),
        calendar_name: z.enum(["primary", "intent", "tangentcode"]),
        title: z.string(),
        start_time: z.string(),
        end_time: z.string().nullable(),
        location: z.string().nullable(),
        is_all_day: z.boolean(),
      }).optional(),
    }),
    timeoutMs: 30_000,
  },
});
